var DOTstring = 'dinetwork { \
keystone->pbr;\
keystone->WebOb;\
keystone->eventlet;\
keystone->greenlet;\
keystone->PasteDeploy;\
keystone->Paste;\
keystone->Routes;\
keystone->Routes;\
keystone->cryptography;\
keystone->six;\
keystone->SQLAlchemy;\
keystone->sqlalchemy_migrate;\
keystone->stevedore;\
keystone->passlib;\
keystone->python_keystoneclient;\
keystone->keystonemiddleware;\
keystone->oslo.cache;\
keystone->oslo.concurrency;\
keystone->oslo.config;\
keystone->oslo.context;\
keystone->oslo.messaging;\
keystone->oslo.db;\
keystone->oslo.i18n;\
keystone->oslo.log;\
keystone->oslo.middleware;\
keystone->oslo.policy;\
keystone->oslo.serialization;\
keystone->oslo.service;\
keystone->oslo.utils;\
keystone->oauthlib;\
keystone->pysaml2;\
keystone->dogpile.cache;\
keystone->jsonschema;\
keystone->pycadf;\
keystone->msgpack_python;\
glance->pbr;\
glance->SQLAlchemy;\
glance->boto;\
glance->decorator;\
glance->eventlet;\
glance->Jinja2;\
glance->keystonemiddleware;\
glance->lxml;\
glance->Routes;\
glance->Routes;\
glance->cryptography;\
glance->pycrypto;\
glance->WebOb;\
glance->greenlet;\
glance->PasteDeploy;\
glance->Paste;\
glance->PrettyTable;\
glance->sqlalchemy_migrate;\
glance->netaddr;\
glance->netifaces;\
glance->paramiko;\
glance->Babel;\
glance->iso8601;\
glance->jsonschema;\
glance->python_cinderclient;\
glance->keystoneauth1;\
glance->python_neutronclient;\
glance->python_glanceclient;\
glance->requests;\
glance->six;\
glance->stevedore;\
glance->setuptools;\
glance->websockify;\
glance->oslo.cache;\
glance->oslo.concurrency;\
glance->oslo.config;\
glance->oslo.context;\
glance->oslo.log;\
glance->oslo.reports;\
glance->oslo.serialization;\
glance->oslo.utils;\
glance->oslo.db;\
glance->oslo.rootwrap;\
glance->oslo.messaging;\
glance->oslo.policy;\
glance->oslo.i18n;\
glance->oslo.service;\
glance->rfc3986;\
glance->oslo.middleware;\
glance->psutil;\
glance->oslo.versionedobjects;\
glance->alembic;\
glance->os_brick;\
glance->os_win;\
glance->castellan;\
nova->pbr;\
nova->SQLAlchemy;\
nova->boto;\
nova->decorator;\
nova->eventlet;\
nova->Jinja2;\
nova->keystonemiddleware;\
nova->lxml;\
nova->Routes;\
nova->Routes;\
nova->cryptography;\
nova->pycrypto;\
nova->WebOb;\
nova->greenlet;\
nova->PasteDeploy;\
nova->Paste;\
nova->PrettyTable;\
nova->sqlalchemy_migrate;\
nova->netaddr;\
nova->netifaces;\
nova->paramiko;\
nova->Babel;\
nova->iso8601;\
nova->jsonschema;\
nova->python_cinderclient;\
nova->keystoneauth1;\
nova->python_neutronclient;\
nova->python_glanceclient;\
nova->requests;\
nova->six;\
nova->stevedore;\
nova->setuptools;\
nova->websockify;\
nova->oslo.cache;\
nova->oslo.concurrency;\
nova->oslo.config;\
nova->oslo.context;\
nova->oslo.log;\
nova->oslo.reports;\
nova->oslo.serialization;\
nova->oslo.utils;\
nova->oslo.db;\
nova->oslo.rootwrap;\
nova->oslo.messaging;\
nova->oslo.policy;\
nova->oslo.i18n;\
nova->oslo.service;\
nova->rfc3986;\
nova->oslo.middleware;\
nova->psutil;\
nova->oslo.versionedobjects;\
nova->alembic;\
nova->os_brick;\
nova->os_win;\
nova->castellan;\
cinder->pbr;\
cinder->SQLAlchemy;\
cinder->boto;\
cinder->decorator;\
cinder->eventlet;\
cinder->Jinja2;\
cinder->keystonemiddleware;\
cinder->lxml;\
cinder->Routes;\
cinder->Routes;\
cinder->cryptography;\
cinder->pycrypto;\
cinder->WebOb;\
cinder->greenlet;\
cinder->PasteDeploy;\
cinder->Paste;\
cinder->PrettyTable;\
cinder->sqlalchemy_migrate;\
cinder->netaddr;\
cinder->netifaces;\
cinder->paramiko;\
cinder->Babel;\
cinder->iso8601;\
cinder->jsonschema;\
cinder->python_cinderclient;\
cinder->keystoneauth1;\
cinder->python_neutronclient;\
cinder->python_glanceclient;\
cinder->requests;\
cinder->six;\
cinder->stevedore;\
cinder->setuptools;\
cinder->websockify;\
cinder->oslo.cache;\
cinder->oslo.concurrency;\
cinder->oslo.config;\
cinder->oslo.context;\
cinder->oslo.log;\
cinder->oslo.reports;\
cinder->oslo.serialization;\
cinder->oslo.utils;\
cinder->oslo.db;\
cinder->oslo.rootwrap;\
cinder->oslo.messaging;\
cinder->oslo.policy;\
cinder->oslo.i18n;\
cinder->oslo.service;\
cinder->rfc3986;\
cinder->oslo.middleware;\
cinder->psutil;\
cinder->oslo.versionedobjects;\
cinder->alembic;\
cinder->os_brick;\
cinder->os_win;\
cinder->castellan;\
neutron->pbr;\
neutron->SQLAlchemy;\
neutron->boto;\
neutron->decorator;\
neutron->eventlet;\
neutron->Jinja2;\
neutron->keystonemiddleware;\
neutron->lxml;\
neutron->Routes;\
neutron->Routes;\
neutron->cryptography;\
neutron->pycrypto;\
neutron->WebOb;\
neutron->greenlet;\
neutron->PasteDeploy;\
neutron->Paste;\
neutron->PrettyTable;\
neutron->sqlalchemy_migrate;\
neutron->netaddr;\
neutron->netifaces;\
neutron->paramiko;\
neutron->Babel;\
neutron->iso8601;\
neutron->jsonschema;\
neutron->python_cinderclient;\
neutron->keystoneauth1;\
neutron->python_neutronclient;\
neutron->python_glanceclient;\
neutron->requests;\
neutron->six;\
neutron->stevedore;\
neutron->setuptools;\
neutron->websockify;\
neutron->oslo.cache;\
neutron->oslo.concurrency;\
neutron->oslo.config;\
neutron->oslo.context;\
neutron->oslo.log;\
neutron->oslo.reports;\
neutron->oslo.serialization;\
neutron->oslo.utils;\
neutron->oslo.db;\
neutron->oslo.rootwrap;\
neutron->oslo.messaging;\
neutron->oslo.policy;\
neutron->oslo.i18n;\
neutron->oslo.service;\
neutron->rfc3986;\
neutron->oslo.middleware;\
neutron->psutil;\
neutron->oslo.versionedobjects;\
neutron->alembic;\
neutron->os_brick;\
neutron->os_win;\
neutron->castellan;\
horizon->pbr;\
horizon->SQLAlchemy;\
horizon->boto;\
horizon->decorator;\
horizon->eventlet;\
horizon->Jinja2;\
horizon->keystonemiddleware;\
horizon->lxml;\
horizon->Routes;\
horizon->Routes;\
horizon->cryptography;\
horizon->pycrypto;\
horizon->WebOb;\
horizon->greenlet;\
horizon->PasteDeploy;\
horizon->Paste;\
horizon->PrettyTable;\
horizon->sqlalchemy_migrate;\
horizon->netaddr;\
horizon->netifaces;\
horizon->paramiko;\
horizon->Babel;\
horizon->iso8601;\
horizon->jsonschema;\
horizon->python_cinderclient;\
horizon->keystoneauth1;\
horizon->python_neutronclient;\
horizon->python_glanceclient;\
horizon->requests;\
horizon->six;\
horizon->stevedore;\
horizon->setuptools;\
horizon->websockify;\
horizon->oslo.cache;\
horizon->oslo.concurrency;\
horizon->oslo.config;\
horizon->oslo.context;\
horizon->oslo.log;\
horizon->oslo.reports;\
horizon->oslo.serialization;\
horizon->oslo.utils;\
horizon->oslo.db;\
horizon->oslo.rootwrap;\
horizon->oslo.messaging;\
horizon->oslo.policy;\
horizon->oslo.i18n;\
horizon->oslo.service;\
horizon->rfc3986;\
horizon->oslo.middleware;\
horizon->psutil;\
horizon->oslo.versionedobjects;\
horizon->alembic;\
horizon->os_brick;\
horizon->os_win;\
horizon->castellan;\
swift->pbr;\
swift->SQLAlchemy;\
swift->boto;\
swift->decorator;\
swift->eventlet;\
swift->Jinja2;\
swift->keystonemiddleware;\
swift->lxml;\
swift->Routes;\
swift->Routes;\
swift->cryptography;\
swift->pycrypto;\
swift->WebOb;\
swift->greenlet;\
swift->PasteDeploy;\
swift->Paste;\
swift->PrettyTable;\
swift->sqlalchemy_migrate;\
swift->netaddr;\
swift->netifaces;\
swift->paramiko;\
swift->Babel;\
swift->iso8601;\
swift->jsonschema;\
swift->python_cinderclient;\
swift->keystoneauth1;\
swift->python_neutronclient;\
swift->python_glanceclient;\
swift->requests;\
swift->six;\
swift->stevedore;\
swift->setuptools;\
swift->websockify;\
swift->oslo.cache;\
swift->oslo.concurrency;\
swift->oslo.config;\
swift->oslo.context;\
swift->oslo.log;\
swift->oslo.reports;\
swift->oslo.serialization;\
swift->oslo.utils;\
swift->oslo.db;\
swift->oslo.rootwrap;\
swift->oslo.messaging;\
swift->oslo.policy;\
swift->oslo.i18n;\
swift->oslo.service;\
swift->rfc3986;\
swift->oslo.middleware;\
swift->psutil;\
swift->oslo.versionedobjects;\
swift->alembic;\
swift->os_brick;\
swift->os_win;\
swift->castellan;\
ceilometer->pbr;\
ceilometer->SQLAlchemy;\
ceilometer->boto;\
ceilometer->decorator;\
ceilometer->eventlet;\
ceilometer->Jinja2;\
ceilometer->keystonemiddleware;\
ceilometer->lxml;\
ceilometer->Routes;\
ceilometer->Routes;\
ceilometer->cryptography;\
ceilometer->pycrypto;\
ceilometer->WebOb;\
ceilometer->greenlet;\
ceilometer->PasteDeploy;\
ceilometer->Paste;\
ceilometer->PrettyTable;\
ceilometer->sqlalchemy_migrate;\
ceilometer->netaddr;\
ceilometer->netifaces;\
ceilometer->paramiko;\
ceilometer->Babel;\
ceilometer->iso8601;\
ceilometer->jsonschema;\
ceilometer->python_cinderclient;\
ceilometer->keystoneauth1;\
ceilometer->python_neutronclient;\
ceilometer->python_glanceclient;\
ceilometer->requests;\
ceilometer->six;\
ceilometer->stevedore;\
ceilometer->setuptools;\
ceilometer->websockify;\
ceilometer->oslo.cache;\
ceilometer->oslo.concurrency;\
ceilometer->oslo.config;\
ceilometer->oslo.context;\
ceilometer->oslo.log;\
ceilometer->oslo.reports;\
ceilometer->oslo.serialization;\
ceilometer->oslo.utils;\
ceilometer->oslo.db;\
ceilometer->oslo.rootwrap;\
ceilometer->oslo.messaging;\
ceilometer->oslo.policy;\
ceilometer->oslo.i18n;\
ceilometer->oslo.service;\
ceilometer->rfc3986;\
ceilometer->oslo.middleware;\
ceilometer->psutil;\
ceilometer->oslo.versionedobjects;\
ceilometer->alembic;\
ceilometer->os_brick;\
ceilometer->os_win;\
ceilometer->castellan;\
}';