var nodes = new vis.DataSet([
{id: 'keystone', label: 'keystone', color:'#97C2FC'},
{id: 'glance', label: 'glance', color:'#FFFF00'},
{id: 'nova', label: 'nova', color:'#FB7E81'},
{id: 'cinder', label: 'cinder', color:'#7BE141'},
{id: 'neutron', label: 'neutron', color:'#6E6EFD'},
{id: 'horizon', label: 'horizon', color:'#C2FABC'},
{id: 'swift', label: 'swift', color:'#FFA807'},
{id: 'ceilometer', label: 'ceilometer', color:'#6E6EFD'},
{id: 'os_brick', label: 'os_brick'},
{id: 'alembic', label: 'alembic'},
{id: 'PasteDeploy', label: 'PasteDeploy'},
{id: 'PrettyTable', label: 'PrettyTable'},
{id: 'Babel', label: 'Babel'},
{id: 'oslo.context', label: 'oslo.context'},
{id: 'os_win', label: 'os_win'},
{id: 'jsonschema', label: 'jsonschema'},
{id: 'oslo.concurrency', label: 'oslo.concurrency'},
{id: 'msgpack_python', label: 'msgpack_python'},
{id: 'oauthlib', label: 'oauthlib'},
{id: 'lxml', label: 'lxml'},
{id: 'oslo.middleware', label: 'oslo.middleware'},
{id: 'eventlet', label: 'eventlet'},
{id: 'oslo.rootwrap', label: 'oslo.rootwrap'},
{id: 'sqlalchemy_migrate', label: 'sqlalchemy_migrate'},
{id: 'six', label: 'six'},
{id: 'netaddr', label: 'netaddr'},
{id: 'Jinja2', label: 'Jinja2'},
{id: 'oslo.serialization', label: 'oslo.serialization'},
{id: 'oslo.service', label: 'oslo.service'},
{id: 'stevedore', label: 'stevedore'},
{id: 'oslo.reports', label: 'oslo.reports'},
{id: 'python_glanceclient', label: 'python_glanceclient'},
{id: 'Paste', label: 'Paste'},
{id: 'websockify', label: 'websockify'},
{id: 'SQLAlchemy', label: 'SQLAlchemy'},
{id: 'oslo.policy', label: 'oslo.policy'},
{id: 'setuptools', label: 'setuptools'},
{id: 'cryptography', label: 'cryptography'},
{id: 'oslo.config', label: 'oslo.config'},
{id: 'pycrypto', label: 'pycrypto'},
{id: 'oslo.cache', label: 'oslo.cache'},
{id: 'oslo.log', label: 'oslo.log'},
{id: 'iso8601', label: 'iso8601'},
{id: 'paramiko', label: 'paramiko'},
{id: 'Routes', label: 'Routes'},
{id: 'pysaml2', label: 'pysaml2'},
{id: 'python_cinderclient', label: 'python_cinderclient'},
{id: 'oslo.versionedobjects', label: 'oslo.versionedobjects'},
{id: 'decorator', label: 'decorator'},
{id: 'oslo.i18n', label: 'oslo.i18n'},
{id: 'python_keystoneclient', label: 'python_keystoneclient'},
{id: 'boto', label: 'boto'},
{id: 'oslo.utils', label: 'oslo.utils'},
{id: 'pbr', label: 'pbr'},
{id: 'passlib', label: 'passlib'},
{id: 'rfc3986', label: 'rfc3986'},
{id: 'castellan', label: 'castellan'},
{id: 'psutil', label: 'psutil'},
{id: 'greenlet', label: 'greenlet'},
{id: 'netifaces', label: 'netifaces'},
{id: 'keystonemiddleware', label: 'keystonemiddleware'},
{id: 'oslo.db', label: 'oslo.db'},
{id: 'oslo.messaging', label: 'oslo.messaging'},
{id: 'requests', label: 'requests'},
{id: 'python_neutronclient', label: 'python_neutronclient'},
{id: 'WebOb', label: 'WebOb'},
{id: 'pycadf', label: 'pycadf'},
{id: 'keystoneauth1', label: 'keystoneauth1'},
{id: 'dogpile.cache', label: 'dogpile.cache'},
]);